### ISSUE TITLE
Review TP 11 - Cynthia DULYMBOIS-LOUISON

### ISSUE THREAD

**Issue by cynthia-DL** [Kwaaac/ProgC#10]
# Rapport de relecture de code

Production soumise à la relecture : **TP 11**
Projet/code produit par **Maxime RODRIGUEZ**
Relecture opérée par **Cynthia DULYMBOIS-LOUISON** le 6 juin 2021

## Concision et propreté des rendus

Les contenus transmis sont à la fois concis et complets. Un maximum d'éléments sont générés 
automatiquement rendant la production minimale en taille lors de sa diffusion.

## Installation et compilation des sources transmises

Le makefile est bien documenté, il propose un haut niveau de verbose et intègre des règles 
pour générer un ou plusieurs contenus annexes (documentation avec doxygen, 
programme de tests supplémentaires, etc).

## Fonctionnalités implantées dans les rendus

Les programmes contiennent quelques preuves de leurs bons fonctionnements.

*Malheureusement, la version que j'ai reçue ne mélangeais pas le Taquin automatiquement...*

## Utilisations et sécurité des programmes produits

Les programmes informent l'utilisateur et le conseillent en cas de mauvaise utilisation.

*Les messages disent précisément ou ce trouve le problème, beau travail !*

## Nommage des éléments dans les productions rendues

Les identifiants apportent de l'information facilitant la compréhension par autrui.

## Efficacité et performance des productions rendues

Les programmes suppriment tout calcul non nécessaire à l'aide d'astuces simples et expliquées.

## Commentaires dans les sources des productions rendues

Des commentaires précisent les parties critiques du code, levant les ambiguïtés.

## derniers commentaires :

*A part une petite erreur d’inattention, c'est un TP exécuté avec brio ! Félicitation !*

**Comment by Kwaaac** [comment]
Merci beaucoup ! La coquille est corrigé dans le commit ci-dessus !
