### ISSUE TITLE
Review TP5

### ISSUE THREAD

**Issue by GuillaumeDOMART** [Kwaaac/ProgC#3]
# Rapport de relecture de code

Production soumise à la relecture : **TP5**
Projet/code produit par **Maxime Rodriguez**
Relecture opérée par **Guillaume DOMART** le 21 décembre 2020

## Concision et propreté des rendus

Les productions transmises sont particulièrement bien structurées et la précision du nommage 
ne laisse aucun doute sur le contenu des répertoires et fichiers.

L'automatisation du changement de valeur pour la variable DEBUG permettrait une utilisation plus simple du programme (système d'option).

## Installation et compilation des sources transmises

Un makefile propre, lisible et complet permet la compilation de toutes les sources sans aucun warning 
et avec les drapeaux -Wall et -ansi (voire -pedantic). Le makefile gère correctement les dépendances 
et intègre une règle pour le nettoyage des produits de compilation.

Manque d'explication dans le makefile

## Fonctionnalités implantées dans les rendus

Les programmes démontrent, durant leurs exécutions, qu'ils réalisent correctement l'intégralité 
du cahier des charges.

## Utilisations et sécurité des programmes produits

Tous les cas d'utilisations normales sont traités correctement par les programmes.

Ne gère pas les cas où la taille d'un tableau est négative

## Nommage des éléments dans les productions rendues

Les identifiants apportent de l'information facilitant la compréhension par autrui.

## Efficacité et performance des productions rendues

Les programmes suppriment tout calcul non nécessaire à l'aide d'astuces simples et expliquées.

Quelques fonctions sont plus simplifiables

## Commentaires dans les sources des productions rendues

Les programmes sont correctement commentés.

Peu apporter d'avantages de précisions sur certaines fonctions complexes 

## derniers commentaires :

Programme très bien structuré, bonne lisibilité mais pourrait être d'avantages commenté notamment pour certaines fonctions complexes qui nécessitent plusieurs relectures pour une bonne compréhension. Un plus grand nombre de test serait apprécié notamment pour gérer les cas générant des erreurs (taille de tableau négative).

**Comment by Kwaaac** [comment]
Merci beaucoup de ta review, je regarde tout ça, et je fais les modifications nécessaires !

**Comment by Kwaaac** [comment]
c447e4e1c3d1d3004d04156b8da1b8f876f3d46f

**Comment by Kwaaac** [comment]
Je viens de réaliser le commit suivant qui corrige les éléments que tu as mentionner dans ta review: 5c33148b50388ad7f924be6c0eed7fba6e1935c4
Si tu peux y jeter un oeil pour me dire ce que tu en penses, ça serai super !
