### ISSUE TITLE
Review TP6

### ISSUE THREAD

**Issue by GuillaumeDOMART** [Kwaaac/ProgC#4]
# Rapport de relecture de code

Production soumise à la relecture : **TP6**
Projet/code produit par **Maxime RODRIGUEZ**
Relecture opérée par **Guillaume DOMART** le 2 janvier 2021

## Concision et propreté des rendus

Les contenus transmis sont à la fois concis et complets. Un maximum d'éléments sont générés
automatiquement rendant la production minimale en taille lors de sa diffusion.

## Installation et compilation des sources transmises

Le makefile est bien documenté, il propose un haut niveau de verbose et intègre des règles
pour générer un ou plusieurs contenus annexes (documentation avec doxygen,
programme de tests supplémentaires, etc).

## Fonctionnalités implantées dans les rendus

Les programmes démontrent, durant leurs exécutions, qu'ils réalisent correctement l'intégralité
du cahier des charges.

## Utilisations et sécurité des programmes produits

Les programmes ne produisent pas d'erreur même en cas d'utilisation non conforme.

## Nommage des éléments dans les productions rendues

Les identifiants suivent des règles de nommages sur tout le code de manière cohérente.

Attention aux noms des variables (par exemple "*t", dans le main du fichier "array.c"), avoir une variable "a" ou "b" n'est pas forcément dérangeant dans un petit  programme mais l'est bien d'avantage dans un programme à plus grande échelle.

## Efficacité et performance des productions rendues

Les programmes suppriment tout calcul non nécessaire à l'aide d'astuces simples et expliquées.

N'a pas pu améliorer la performance des algorithmes tout en respectant les consignes.

## Commentaires dans les sources des productions rendues

Les commentaires présentent les intentions et justifient les choix de programmation de l'auteur.

Commentaires parfaits ! Expliquent correctement le rôle de chaque fonction tout en précisant les entrée et sorties. Certaines fonctions comportent également des warning pour certains cas d'utilisation créées par des utilisateurs taquins !

## derniers commentaires :

Rappel concernant la modularisation :
Ne faites des "include que dans les fichiers .h. Ne l'intégrez au .c que si l'intégrer au .h créerait une boucle d'inclusion (a.h -> b.h -> a.h = erreur), dans le cas ou vous intégrez un fichier et non pas une librairie ("#include " est à faire de préférence dans le .h).

**Comment by Kwaaac** [comment]
Merci pour le rappel, je n'en n'avais pas connaissance (et roh ça va pour le "*t", c'est la seule variable qui est pas bien :c, mais entièrement d'accord avec toi sur ce point là !).

Merci pour la review!
