### ISSUE TITLE
Review TP11 Barbé

### ISSUE THREAD

**Issue by Romain-Barbe** [Kwaaac/ProgC#9]
# Rapport de relecture de code

Production soumise à la relecture : **TP11-Jeu de taquin**
Projet/code produit par **Maxime Rodriguez**
Relecture opérée par **Romain Barbé** le 5 juin 2021

## Concision et propreté des rendus

Les productions transmises sont particulièrement bien structurées et la précision du nommage 
ne laisse aucun doute sur le contenu des répertoires et fichiers.

## Installation et compilation des sources transmises

Le makefile est bien documenté, il propose un haut niveau de verbose et intègre des règles 
pour générer un ou plusieurs contenus annexes (documentation avec doxygen, 
programme de tests supplémentaires, etc).

Possibilité agréable de générer de la documentation avec doxygen en utilisant la commande "make doc"
Manque malheureusement la documentation sur bord.h

## Fonctionnalités implantées dans les rendus

Les programmes démontrent, durant leurs exécutions, qu'ils réalisent correctement l'intégralité 
du cahier des charges.

## Utilisations et sécurité des programmes produits

Tous les cas d'utilisations normales sont traités correctement par les programmes.

Quand appel du programme sans image en argument, précision qu'il manque un fichier en argument
Je pense qu'une précision sur le type de fichier à donner en argument aurait été un plus
J'ai en revanche réussi à faire un core dumped en donnant un fichier autre qu'un fichier image en argument

## Nommage des éléments dans les productions rendues

Les identifiants apportent de l'information facilitant la compréhension par autrui.

## Efficacité et performance des productions rendues

Les programmes sont basés sur des algorithmes attendues.

## Commentaires dans les sources des productions rendues

Des commentaires précisent les parties critiques du code, levant les ambiguïtés.

Présence de commentaires dans les fichiers ainsi qu'une doc très complète générée avec doxygen avec la commande "make doc"

## derniers commentaires :

Problème de segmentation lorsqu'on termine le jeu ; cela vient probablement de la libération des éléments alloués pour le jeu

**Comment by Kwaaac** [comment]
Merci de la review, tout est corrigé dans le commit ci-dessus !
